[package]
name = "rust-raytracer"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
assert-eq-float = "0.1.4"
thiserror = "2.0.17"

[workspace]
members = ["crates/core", "crates/cli", "crates/wasm", "crates/openscad"]
