[package]
name = "caustic-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
indicatif = "0.18.3"
num_cpus = "1.17.0"
caustic-core = { path = "../core" }
caustic-openscad = { path = "../openscad" }
thread-priority = "3.0.0"
thiserror = { workspace = true }
ariadne = "0.6.0"
