[package]
name = "caustic-openscad"
version = "0.1.0"
edition = "2024"

[dependencies]
rand_mt = "5.0.0"
caustic-core = { path = "../core" }

[dev-dependencies]
assert-eq-float = { workspace = true }
